name: Automated build

on: [push, pull_request]

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - uses: https://github.com/gradle/actions/wrapper-validation@v5.0.0
      - uses: https://github.com/actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
      - name: Setup Gradle
        uses: https://github.com/gradle/actions/setup-gradle@v5.0.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/multiversion' && github.ref != 'refs/heads/dev' }}


      - name: Build
        run: ./gradlew build collectBuilds --stacktrace --no-daemon

      - name: Upload a Build Artifact
        uses: https://data.forgejo.org/forgejo/upload-artifact@v5
        with:
          # Artifact name
          name: AxolotlClient-automation
          path: builds/*.jar
