name: Release
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    name: "Tagged Release"
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-24.04
    permissions:
      contents: write
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6

      - uses: https://github.com/gradle/actions/wrapper-validation@v5.0.0

      - uses: https://github.com/actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25

      - name: Setup Gradle
        uses: https://github.com/gradle/actions/setup-gradle@v5.0.0
        with:
          cache-read-only: true

      - name: Build
        run: ./gradlew build collectBuilds --stacktrace

      - name: Generate Version Changelog
        run: ./gradlew generateVersionChangelog

      - name: Create Release
        uses: https://code.forgejo.org/crueter/forgejo-release@05d41bd91513e4e02b6f6b7167706c31373ffbd6
        with:
            direction: upload
            release-dir: builds/
            release-notes-file: build/changelog

      - name: Publish to Modrinth/CurseForge
        run: ./gradlew publishMods
        env:
            MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
            CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Publish to Maven
        run: ./gradlew publish -PowlMavenPassword=${{ secrets.MAVEN_PASSWORD }} -PowlMavenUsername=${{ secrets.MAVEN_USERNAME }}
